version: '3.5'
services:
  isard-authentication:
    container_name: isard-authentication
    image: ${DOCKER_IMAGE_PREFIX}authentication:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.11
    volumes:
      - "/opt/isard/authentication/keys:/keys"
      - "/opt/isard/authentication/metadata:/metadata"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
