version: '3.5'
services:
  isard-static:
    volumes:
    - ${BUILD_ROOT_PATH}/docker/static/spice-web-client:/usr/share/nginx/html/static/spice-web-client
    - ${BUILD_ROOT_PATH}/docker/static/noVNC:/usr/share/nginx/html/static/noVNC
  isard-frontend-dev:
    container_name: isard-frontend-dev
    image: node:18
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      isard-network:
    working_dir: /usr/local/src/isard-frontend/
    environment:
      CYPRESS_CACHE_FOLDER: /usr/local/src/isard-frontend/node_modules/.cache/cypress
    command: sh -c "yarn install && yarn serve"
    volumes:
    - ${BUILD_ROOT_PATH}/frontend/:/usr/local/src/isard-frontend/
  isard-cypress:
    volumes:
      - ${BUILD_ROOT_PATH}/frontend/:/usr/local/src/isard-frontend/
