version: '3.5'
services:
  isard-cypress:
    container_name: isard-cypress
    image: ${DOCKER_IMAGE_PREFIX}cypress:${DOCKER_IMAGE_TAG-latest}
    profiles:
      - test
    depends_on:
      isard-api:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    network_mode: host
