version: '3.5'
services:
  isard-webapp:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: webapp/docker/Dockerfile
      target: production
      args:
        SRC_VERSION_ID: $SRC_VERSION_ID
        SRC_VERSION_LINK: $SRC_VERSION_LINK
